apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mydpl
spec:
  selector:
    matchLabels:
      net: cip-comm
  replicas: 1
  template:
    metadata:
      labels:
        net: cip-comm
    spec:
      containers:
      - name:  con01
        image: nginx
        ports:
         - containerPort: 80
   