kind: ReplicationController
apiVersion: v1
metadata:
  name: recpod
spec:
  replicas: 2
  selector:
    rcname: rcpods
  template:
    metadata:
      name: mypod
      labels:
        rcname: rcpods
    spec:
      containers:
        - name: ng
          image: nginx:latest
          ports:
            - containerPort: 80